[Types] Fix error TS2309 in index.d.ts
Using simple-encryptor with typescript, I can't build the code due to error `TS2309: An export assignment cannot be used in a module with other exported elements` due to `export = encryptorCreator` in `index.d.ts`

Tested on typescript 2.9.2